---
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
matrix:
  allowed_failures:
  - python: "nightly"
# command to install dependencies
install: pip install `case ${TRAVIS_PYTHON_VERSION} in 2*) echo argparse importlib; esac` behave
# command to test
script: behave
